### ISSUE TITLE
Template Page for post field (75 pts)

### ISSUE THREAD

**Issue by yinonrousso** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#1]
Add a template for sellers to post items to the main page. This template will need the following input fields:

- [ ] Title
- [ ] Description
- [ ] Contact info

**Comment by wilsonmui** [comment]
Note: This template will represent a post and will later be used in a list. Assume price is included in description. Should be able to dynamically load values into its fields. (Values in fields should not be hard-coded.)

100 pts

**Comment by wilsonmui** [comment]
75 pts

**Comment by pconrad** [comment]
@yinonrousso there is no comment with a pull request.

See my comments on Issue #20

**Comment by juangonzalez20** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/5)
