### ISSUE TITLE
Create a "Make New Post" process. (200 points)

### ISSUE THREAD

**Issue by juangonzalez20** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#10]
Need to create a process in which a seller/giver can make a new post. I think the the simplest solution would just be to create a new page dedicated to making new posts. On that page, the user would have to input required info (discussed in #1) to make a valid post. When all that is done they could press a button to submit it to be reviewed and if it's a valid post add it to the database.

**Comment by wilsonmui** [comment]
A user can make/submit a new post with required info.
Valid new post should be added to the database. 
A reviewer should be able to see and approve this post. Once it is approved, the post will be in the database as a new item.

300 points

**Comment by wilsonmui** [comment]
200 points, some parts are covered by #8 and will require #8 to be completed for this to work.

**Comment by juangonzalez20** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/5)

**Comment by zaleshaiker** [comment]
[pull request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/6)

**Comment by yinonrousso** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/7)
