### ISSUE TITLE
View posts from database (400 points)

### ISSUE THREAD

**Issue by juangonzalez20** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#11]
Need to able to fetch the info from the database (issue #9 ) so that we can construct individual post that will populate the "Current Post" page or whatever way we choose to present the post. For a MVP (minimal viable product) we could just have a list of collapsed/abbreviated items (as discussed in issue #2) which a user can click for more info (issue #4). Would have to create another page for the expanded view associated with the collapse view.

**Comment by wilsonmui** [comment]
Users should be able to see content from database in a list of item posts. Clicking on the post will allow user to go to a new page with the information pertaining to the item. 

400 points

**Comment by RamiPinto** [comment]
For the MVP we think that is not essential to have a detailed view. We have done the first part of the issue ("Users should be able to see content from database in a list of item posts") but not the second one. Should we create a new issue or could this one be modified?

**Comment by wilsonmui** [comment]
For completing the first part of this issue, the part you described, I will estimate 200 points.

**Comment by zaleshaiker** [comment]
[pull request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/6)
