### ISSUE TITLE
Skunkwork for integrating database using MongoDB

### ISSUE THREAD

**Issue by RamiPinto** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#12]

**Comment by wilsonmui** [comment]
Should demonstrate MongoDB in the context of Spring boot and work on its own Heroku app. Should be able to demonstrate that features work. (adding/removing items)

200 points

**Comment by RamiPinto** [comment]
https://github.com/ucsb-cs56-f18/sw-buy-sell-giveaway-issue12

**Comment by wilsonmui** [comment]
Please give instructions on how to run application, referencing the MongoDB tutorial instructions for setting up MongoDB will be fine.

**Comment by wilsonmui** [comment]
https://github.com/ucsb-cs56-f18/sw-buy-sell-giveaway-issue12
