### ISSUE TITLE
Integrate Skunkworks for Git Oauth into webapp

### ISSUE THREAD

**Issue by yinonrousso** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#19]
Create a basic setup for Oauth for admins, approved members, and the general public. Base Oauth off of https://github.com/ucsb-cs56-pconrad/spring-boot-github-oauth-demo02
* As an admin 
* I can delete any post
* so that I can follow up with the user guidelines.
* As a member(poster)
* I can mark my post ready for deletion 
* so that people will stop contacting me. 
* As a general user
* I can view posts.

**Comment by wilsonmui** [comment]
200 points

**Comment by yinonrousso** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/7)
