### ISSUE TITLE
Create basic abbreviated item template (item)

### ISSUE THREAD

**Issue by zholoien** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#2]
Multiple items following this item template will be listed on top of the browser template

**Comment by wilsonmui** [comment]
What should the item template contain?

**Comment by juangonzalez20** [comment]
For the minimum viable product it should probably only contain the name of the item. The other info like, the seller contact info would be in the expanded item view.

**Comment by wilsonmui** [comment]
merged with issue #11
