### ISSUE TITLE
Template Page for Home Page to display posts (100 pts)

### ISSUE THREAD

**Issue by zaleshaiker** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#20]
Create a template for the home page so that it looks nice. This includes the template for each post. The home page will contain all of the posts that users submit, so that viewers can browse through them. This page is dependent on the post page as each post is displayed on the home page. This task is to create a proper format for viewing each post. User story: As a viewer I can see posts

**Comment by pconrad** [comment]
There is no comment on this issue with a link to a pull request. 

Wilson already moved this back from Ready for QA to In Progress once.  And when he did, he sent you this message: 

<img width="700" alt="message-from-wilson" src="https://user-images.githubusercontent.com/1119017/49413620-5f542200-f725-11e8-9cd0-71e83ca84488.png">

@yinonrousso Can you help me understand why you dragged it back into "Ready for QA" without adding a comment with a link to pull request?

I'm dragging it back to In Progress myself.  Please review the TWO piazza messages I sent stressing the need for pull request before dragging this back into Ready for QA. 

And ONLY THE MENTORS may drag things into ready for grading.

**Comment by juangonzalez20** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/5)
