### ISSUE TITLE
Deploy on Heroku, link in ReadMe

### ISSUE THREAD

**Issue by wilsonmui** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#21]
Deploy your web app on Heroku and put a link on the ReadMe. Your web app should should be working with the current completed features. Also, please write the commands for building/running your web app.

100 points

**Comment by pconrad** [comment]
@yinonrousso: what pull request corresponds to this issue being in the Ready for QA column?  
This issue should NOT be in Ready for QA without a comment with a link to a specific pull request.

If a comment with a specific pull request doesn't appear, @wilsonmui  should put this issue BACK into the In-Progress column.

**Comment by pconrad** [comment]
Never mind.. I'm dragging it back myself.

**Comment by juangonzalez20** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/5)
