### ISSUE TITLE
Create Test Cases for PostVerifier.java (100)

### ISSUE THREAD

**Issue by zholoien** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#22]

**Comment by wilsonmui** [comment]
What is PostVerifier.java and how will you test it?

**Comment by zholoien** [comment]
Post Verifier has one method that takes a Posting object and checks that all fields are not empty. Returns a boolean. Testing posts with empty fields; also useful for testing JaCoco

**Comment by derektkbang** [comment]
I added test cases for every type of verification to confirm that it recognizes when a field is empty

**Comment by wilsonmui** [comment]
What are all the issues that this pull request is implementing?

**Comment by derektkbang** [comment]
issue22 and issue15, there's no issue for testing posting

**Comment by wilsonmui** [comment]
There seems to be a compilation error when I try running the Jacoco test.

**Comment by wilsonmui** [comment]
Whoops I've been thinking I was on the pull request page, my apologies. However, pull request #3 is not compiling.

**Comment by derektkbang** [comment]
I am currently waiting for the rest of my team to properly update their methods, as the Posting object was changed in between users

**Comment by derektkbang** [comment]
issue22 appears to be up to date and functioning properly
