### ISSUE TITLE
Skunkworks for Github OAuth (200)

### ISSUE THREAD

**Issue by wilsonmui** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#23]
Create a standalone Heroku app implementing Github Oauth. This application should run on Heroku, and demonstrate features that Buy-Sell app will use, such as logging in as admin or poster. 

200 points

**Comment by pconrad** [comment]
@yinonrousso there is no pull request.  So I am going to drag this back into In-Progress.

Please read the two previous Piazza posts, especially the latest one, and comply with those instructions before dragging this back into ready for QA.

**Comment by pconrad** [comment]
@RamiPinto 
There should be a pull request.  This Piazza post explains how to make a pull request for a Skunkworks project.

Until there is a Pull request, this should NOT be in the ready for QA column.   It is NOT ready for QA until there is a pull request.
