### ISSUE TITLE
Create item detailed view page (50 points)

### ISSUE THREAD

**Issue by RamiPinto** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#4]
You can see more details about the item

**Comment by wilsonmui** [comment]
Please be more specific; what additional information will this show that the item template does not?

**Comment by juangonzalez20** [comment]
This template would contain, at minimum, info like the name of the product and seller/giver contact info (Maybe a phone number and email?)

**Comment by wilsonmui** [comment]
Make the template load information from some kind of database to get more points. 

50 points

**Comment by juangonzalez20** [comment]
Info would be pulled from database (issue #9) to populate template.

**Comment by wilsonmui** [comment]
merged with issue #11
