### ISSUE TITLE
Create database for the webapp (400 points)

### ISSUE THREAD

**Issue by juangonzalez20** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#7]
Need to create a database to store posts people will be making.
Entries in that database should at minimum contain info about.

- Item name

- Seller/Giver contact info (phone number and or email)

**Comment by wilsonmui** [comment]
Create and integrate a database into project. The database should be appropriately structured. Should be possible to retrieve and modify elements in the database. 

Create basic methods to add post to database and remove post. These methods should do what is expected, changes will be reflected from database. Does not have to be visible to users, this is for development purposes.

400 points

**Comment by RamiPinto** [comment]
https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/4

**Comment by zaleshaiker** [comment]
[pull request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/6)
