### ISSUE TITLE
Review and approve post (200 points)

### ISSUE THREAD

**Issue by juangonzalez20** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#8]
When a user creates a new post we need to able to add that new post into our existing database. We should probably verify that it has all the required info to make it a valid post (name, contact info).

**Comment by wilsonmui** [comment]
A reviewer can see posts pending approval. The post can be approved, and once approved, it will be in the database as available.

200 points

**Comment by juangonzalez20** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/5)

**Comment by zaleshaiker** [comment]
[pull request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/6)

**Comment by yinonrousso** [comment]
[Pull Request](https://github.com/ucsb-cs56-webapps/ucsb-cs56-buy-sell-giveaway/pull/7)
